services:
    app-nginx:
        container_name: app-nginx
        build: ./docker/nginx
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - laravel_net

    app-php:
        container_name: app-php
        build: ./docker/php
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
        - laravel_net

    db:
        container_name: postgres_db
        restart: unless-stopped
        build: docker/db
        environment:
            POSTGRES_DB: app_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./docker/db/data:/var/lib/db
        networks:
            - laravel_net

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - db
        networks:
            - laravel_net

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - laravel_net

    minio:
        image: minio/minio
        container_name: minio
        restart: unless-stopped
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
        ports:
            - "9002:9000"
            - "9001:9001"
        networks:
            - laravel_net

volumes:
    db_data:
    minio_data:

networks:
    laravel_net:
        driver: bridge
